name: test

on:
  push:  # Trigger the workflow on a push event
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run custom action
        uses: ./  # Refers to a local custom action
